<?php
	$querymatchexp = R::getAll( "
	$selectFields
	,MATCH ($NUMBERFIELD,$TEXTFIELD1,$TEXTFIELD2)
	AGAINST ('$query' IN NATURAL LANGUAGE MODE WITH QUERY EXPANSION) as Score
	FROM `$TABLE`
	WHERE $NUMBERFIELD IS NOT NULL AND $NUMBERFIELD <> '' 
	AND MATCH ($NUMBERFIELD,$TEXTFIELD1,$TEXTFIELD2)
	AGAINST ('$query' IN NATURAL LANGUAGE MODE WITH QUERY EXPANSION);
	");
	echo "<pre>";
	echo "<h1>MATCH IN NATURAL LANGUAGE MODE WITH QUERY EXPANSION Suche $query </h1>";
	echo build_table($querymatchexp);
	echo "</pre>";
?>